language: java

jdk:
  - openjdk8

env:
  global:
    - secure: vl3hybmJnMrIF4NY53oUFvJImo0BBhGlIUQziLc4LVlh4URhcRjpyIs0QtEiW1luWYoZ1WhEOmixbJ5uehYMCpr9VEP4ZF+hYv9t4NEIxOi7Hnk/q5ZWfqIevof+pT/TR9M/IQbr6FCohOB37PPavH8TvE6Yx23ohwVHDoBfwJp2rWPrp4D7Jf6EquGopGdfNSIC+LMMVD61OLNaSpakhgUKFreuHEJb1pB1uRuxRYbBIobhTB63APbitnDuVVQSDFsqHTyhnbv3IgQnBgE/NfM663Cdf/khCBbyHnBdtxSMynEwoaf36WPqPQWvhgKFRxM7qnG2G9v2DGjx1tlojpp67pt2SV/t7PrPYixWv6dDJX/E9orQjta3DNZoJN26um1Um6810qBN4iloGaLasK+dtj1J7pqE5aFmu8JgGKJUVSdBTCJdI1lRyhxr1UMAhAbLbbaZrEcAmMlkDzfBLrWypXsbz4mn5Iqpodddy/Mgb17w5bTa6VgHMug7lbx9alh9/fe27x/ZHC+eo+Hf0eLl3DqM6JGzRn3XYgLEhAQWDOtRik8A+bYHBcxBjPQDZfeqkUQsZcC9BB31JMiWMQ082njt+TwBUh/9V1RDv0uptdnHsAvzD4ahAN7/z4HrE1ADnY8obK5hW+C6GCkKP3mFb0Uo/79iE/hm1BML3fc=
    - secure: gAXPrSgcU5hWa8SpsRtmrazl7S/Swwq9b8rCsLIetNtu5a+yEOihyAws1z32o7QWi18EyHInu/wqKRIyi5NJHerQugSOECnL/JNeAZn7GIetG1y6wmSKCo70ct10Do57+ts5q0XOTurrCUIdySDQhvCgFzoWo9HYch8bGORtgACg7FpkL0HZbWXOAr3GCEl/v9ld2ozZ5pzejZXa1HcgVEQ+DaBz6DzTlxJOXqnBZ4bHg+fBhgsdO/BMsvpag2h3WTX4LsAWOB9K71FP/TtKsaxUjvsBvNeACQEVISAYCDio9lkfNxvoMTP4HwDJ1wrzSHYVABcXa3etpB+HXFt81cF+R1wzZpU5Ly3+VKrnzsWv3LnGXDM2b/GvMl2N42Lk4GBy+c8TUVvdzMBf4iskyRGEopNoMBoD/58yVs82svIyK2Cr7J9L+vU9c7vAfZELda6rDEg0J4aXXlanoEj9aMoFbM9tVd8LfWNr3sagM2PaiicRu5eukBaiEnfDespuGS5+ReR3ExNDx9IrDMBxcr2dxWctGrX/uRq8j2t6cN+mKwbZAcm/ubLdV+4OeTTvcbIaXIPl9xdXj9pKoD0RIi+boXuAHzUaJOcY9bcA5qhADvGi8gyoOmYL8L+BRZ83qVYsXkHF8RaqjIy4JMd5umZO1gSme9vMBO6wAGjvLYI=

script:
  - "./gradlew check"
  - "./gradlew jacocoTestReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./deploy.sh